Repository ezsystems/ezcommerce, pull requests merged in 2020-12, with the labels that each got.

#41 Dropped obsolete parameter referencing non-existent path
  config/packages/ezcommerce/ecommerce_parameters.yaml
Labels: Improvement, QA approved, Ready for review

#43 Reverted correct config/packages/overrides/* config files
  config/packages/overrides/generic.php
  config/packages/overrides/platformsh.php
Labels: Bug

#47 EC-315: Enabled BasketBundle
  config/bundles.php
Labels: Improvement

#48 Added BasketBundle routing
  config/routes/ezcommerce.yaml
Labels: Bug
