Repository ezsystems/ezcommerce, pull requests merged in 2020-07, with the labels that each got.

#18 EC-171: Added ezcommerce-page-builder package to meta repository
  composer.json
  config/bundles.php
Labels: enhancement

#19 EC-97: Fixed Components content tree root
  config/packages/ezplatform.yaml
Labels: bug

#21 EC-190: Added support for SOLR 7.7
  .env
  install-solr.sh
Labels: bug

#23 EC-193: Fixed IbexaPlatformCommerceAdminUiBundle namespace
  config/bundles.php
  config/routes/ezcommerce.yaml
Labels: bug

#22 EC-126: Replaced SisoVariantTypeBundle with IbexaPlatformCommerceFieldtypesBundle
  config/bundles.php
Labels: Rebase Required
